// TODO: This file needs to be generated by FlutterFire CLI
// Run the following commands:
// 1. Install Firebase CLI: npm install -g firebase-tools
// 2. Login to Firebase: firebase login
// 3. Run: flutterfire configure
//
// Or manually create a Firebase project at https://console.firebase.google.com
// and copy the configuration values below

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web; // Use web config for Windows
      case TargetPlatform.linux:
        return web; // Use web config for Linux
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase Web configuration - CountX Project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCgeTs0RClQkW3hqwJaTDKz-HG63vZNg',
    appId: '1:124112999062:web:e1d85fe2de0314fa5f28b7',
    messagingSenderId: '124112999062',
    projectId: 'countx-f6b37',
    authDomain: 'countx-f6b37.firebaseapp.com',
    storageBucket: 'countx-f6b37.firebasestorage.app',
    measurementId: 'G-HGFMXLQPRS',
  );

  // Firebase iOS configuration - CountX Project
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCgeTs0RClQkW3hqwJaTDKz-HG63vZNg',
    appId: '1:124112999062:ios:0ed08ec1c6b5cdeb5f28b7',
    messagingSenderId: '124112999062',
    projectId: 'countx-f6b37',
    storageBucket: 'countx-f6b37.firebasestorage.app',
    iosBundleId: 'com.x.countx',
  );

  // Firebase Android configuration - CountX Project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiCgeTs0RClQkW3hqwJaTDKz-HG63vZNg',
    appId: '1:124112999062:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '124112999062',
    projectId: 'countx-f6b37',
    storageBucket: 'countx-f6b37.firebasestorage.app',
  );

  // Firebase macOS configuration - CountX Project
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCgeTs0RClQkW3hqwJaTDKz-HG63vZNg',
    appId: '1:124112999062:ios:0ed08ec1c6b5cdeb5f28b7',
    messagingSenderId: '124112999062',
    projectId: 'countx-f6b37',
    storageBucket: 'countx-f6b37.firebasestorage.app',
    iosBundleId: 'com.x.countx',
  );
}
